# docker-compose.yml
services:
  napcat:
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - MODE=astrbot
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - 6099:6099
    container_name: napcat
    restart: always
    image: mlikiowa/napcat-docker:latest
    volumes:
      - ./data:/AstrBot/data
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ
    networks:
      - astrbot_network

  astrbot:
    environment:
      - TZ=Asia/Shanghai
    image: soulter/astrbot:latest
    container_name: astrbot
    restart: always
    ports:
      - "6185:6185"
    volumes:
      - ./data:/AstrBot/data
    networks:
      - astrbot_network

  gsuid-core:
    image: docker.cnb.cool/gscore-mirror/gsuid_core:latest
    restart: always
    container_name: gsuid-core
    volumes:
      - ./gsuid_core:/app
      - ./gsuid_data:/app/data
      - ./gsuid_start/gsuid_start.sh:/start
      - ./gsuid_plugins:/app/gsuid_core/plugins
    ports:
      - 8765:8765
    environment:
      UV_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple/
      HOME: /app/data
    networks:
      - astrbot_network

networks:
  astrbot_network:
    driver: bridge